#integrates Travis so that code and documentation is held to the proper standards
language: python
python:
  - "3.6"

cache:
  directories:
    - $HOME/.pip-cache/

#install mdl for checking Markdown in README.md
before_install:
  - gem install mdl
notifications:
  email: never

install:
  - pip install --upgrade pip
  - pip install beautifulsoup4
  - pip install requests
  - pip install --upgrade pandas
  - pip install imgkit


script:
  - mdl README.md
  - python main.py
    on:branch: master


after_success:
  coveralls
